server:
  port: 8092
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservation?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: chicago
    tomcat.test-while-idle: true
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
