aws:
  accessKey: AKIAQHVO7UZPVJBNCDUF
  secretKey: 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

server:
  port: 8091

queue:
  sqsTest: https://sqs.us-east-1.amazonaws.com/016473106015/mail_reservation

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservation?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: chicago
    tomcat.test-while-idle: true
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
